name: MAKE_RELEASE_PULL_REQUEST

inputs:
  version:
    description: "Target release version"
    required: true
    type: string
  github_token:
    description: "GitHub token for github cli"
    required: true

outputs:
  pr_number:
    description: "Release PR's number"
    value: ${{ steps.make-pr.outputs.pr_number }}

runs:
  using: "composite"
  steps:
    - name: Set to env
      run: |
        echo "NEW_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=${{ inputs.github_token }}" >> $GITHUB_ENV
      shell: bash
    - name: Switch release branch
      run: |
        git switch -c "release/$NEW_VERSION"
      shell: bash
    - name: Increment version
      run: |
        ./.github/script/bump_version.sh "$NEW_VERSION"
        git config user.name "actions-user"
        git config user.email "action@github.com"
        git add .
        git commit -m "Bump version to $NEW_VERSION"
        git push origin $(git branch --show-current)
      shell: bash
    - name: Change milestone title
      id: milestone
      run: |
        milestone_number=$(gh api repos/${{ github.repository }}/milestones -q ".[] | select(.title == \"Next Release\") | .number")
        echo "number=$milestone_number" >> $GITHUB_OUTPUT
        echo "$milestone_number"
        gh api -X PATCH repos/${{ github.repository }}/milestones/$milestone_number -F title="Release $NEW_VERSION"
        echo "Fixed"
        gh api -X POST repos/${{ github.repository }}/milestones -F title="Next Release"
        echo "Created"
      shell: bash
    - name: Make Pull Request
      id: make_pr
      run: |
        ./.github/script/make_release_pr.sh "$NEW_VERSION"
        echo "pr_number=$(gh pr list -s open --json number,title,milestone --jq '.[] | select(.milestone.number == ${{ steps.milestone.outputs.number }}) | .number')" >> $GITHUB_OUTPUT
      shell: bash
