name: RELEASE

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Target release version"
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NEW_VERSION: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Change
        run: |
          milestone_number=$(gh api repos/${{ github.repository }}/milestones -q ".[] | select(.title == \"Next Release\") | .number")
          gh api repos/${{ github.repository }}/milestones/$milestone_number -X PATCH -F title="Release $NEW_VERSION"
          gh api repos/${{ github.repository }}/milestones -X POST -F title="Next Release"
      - name: Make PullRequest
        id: make-pr
        uses: ./.github/actions/make_release_pull_request
        with:
          version: ${{ inputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
