name: RELEASE

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Target release version"
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NEW_VERSION: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Make PullRequest
        id: make-pr
        uses: ./.github/actions/make_release_pull_request
        with:
          version: ${{ inputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo
        run: |
          echo "${{ steps.make-pr.outputs.pr_number }}"
