name: RELEASE

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Target release version"
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make PullRequest
        uses: ./.github/actions/make_release_pull_request
        with:
          version: ${{ inputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
