name: RELEASE

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Target release version"
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NEW_VERSION: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Change milestone title
        run: |
          milestone_number=$(gh api repos/${{ github.repository }}/milestones -q ".[] | select(.title == \"Next Release\") | .number")
          gh api -X PATCH repos/${{ github.repository }}/milestones/$milestone_number -f title="Release $NEW_VERSION"
          gh api -X POST repos/${{ github.repository }}/milestones -f title="Next Release"

      - name: Make PullRequest
        id: make_pr
        uses: ./.github/actions/make_release_pull_request
        with:
          version: ${{ inputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo
        run: |
          echo "${{ steps.make_pr.outputs.pr_number }}"
